import os
from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from datetime import datetime

class ExportService:
    def __init__(self, output_dir: str = "exports"):
        self.output_dir = output_dir
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)

    def generate_report(self, document_id: str, insight_data: dict) -> str:
        """
        Generates a professionally formatted DOCX report from the RAG pipeline output.
        """
        doc = Document()

        # Document styles
        style = doc.styles['Normal']
        font = style.font
        font.name = 'Arial'
        font.size = Pt(11)

        # ---------------------------
        # COVER PAGE
        # ---------------------------
        doc.add_heading('RAGForge Legal Intelligence Review', 0)
        
        doc.add_paragraph(f"Document Name: {document_id}")
        doc.add_paragraph(f"Generated On: {datetime.now().strftime('%d %B %Y, %H:%M')}")
        
        profile = insight_data.get('contract_profile', {})
        if profile:
            doc.add_heading('Contract Overview', level=1)
            p = doc.add_paragraph()
            p.add_run("Agreement Type: ").bold = True
            p.add_run(f"{profile.get('document_type', 'N/A')}\n")
            
            p.add_run("Parties: ").bold = True
            p.add_run(f"{', '.join(profile.get('parties', []))}\n")
            
            p.add_run("Governing Law: ").bold = True
            p.add_run(f"{profile.get('governing_law', 'N/A')}")

        doc.add_page_break()

        # ---------------------------
        # EXECUTIVE SUMMARY
        # ---------------------------
        insights = insight_data.get('insights', {})
        if insights.get('summary'):
            doc.add_heading('Executive Summary', level=1)
            doc.add_paragraph(insights['summary'])

        # ---------------------------
        # FINDINGS & RISKS (Pass 2 output)
        # ---------------------------
        findings = insight_data.get('review_findings', [])
        
        missing_protections = [f for f in findings if f.get('finding_type') == 'missing_protection']
        active_risks = [f for f in findings if f.get('finding_type') != 'missing_protection']

        doc.add_heading('Key Risks & Missing Protections', level=1)

        if missing_protections:
            doc.add_heading('Missing Protections (Needs Drafting)', level=2)
            table = doc.add_table(rows=1, cols=3)
            table.style = 'Light Shading Accent 1'
            hdr_cells = table.rows[0].cells
            hdr_cells[0].text = 'Severity'
            hdr_cells[1].text = 'Protection Type'
            hdr_cells[2].text = 'Legal Analysis'

            for f in missing_protections:
                row = table.add_row()
                row.cells[0].text = str(f.get('severity', '')).upper()
                row.cells[1].text = str(f.get('title', ''))
                row.cells[2].text = str(f.get('explanation', ''))

        if active_risks:
            doc.add_heading('Active Risks (Requires Negotiation)', level=2)
            table = doc.add_table(rows=1, cols=3)
            table.style = 'Light Shading Accent 2'
            hdr_cells = table.rows[0].cells
            hdr_cells[0].text = 'Severity'
            hdr_cells[1].text = 'Clause Reference'
            hdr_cells[2].text = 'Legal Issue & Quotes'

            for f in active_risks:
                row = table.add_row()
                row.cells[0].text = str(f.get('severity', '')).upper()
                
                refs = f.get('clause_refs', [])
                row.cells[1].text = ", ".join(refs) if isinstance(refs, list) else str(refs)
                
                quotes = f.get('source_quotes', [])
                q_text = "\\n\\nSource: \\\"" + "\\\", \\\"".join(quotes) + "\\\"" if quotes else ""
                row.cells[2].text = str(f.get('explanation', '')) + q_text

        doc.add_page_break()

        # ---------------------------
        # LEGAL DISCLAIMER (UPL Shield)
        # ---------------------------
        doc.add_heading('System Information & Legal Disclaimer', level=2)
        disclaimer = doc.add_paragraph()
        run = disclaimer.add_run(
            "IMPORTANT NOTICE: This report was automatically generated by RAGForge Legal Intelligence Engine. "
            "It is designed to assist attorneys in accelerating human document review. "
            "This report does NOT constitute legal advice. You must verify all findings and source quotes "
            "manually before advising clients. Artificial Intelligence can produce inaccurate or 'hallucinated' outputs."
        )
        run.italic = True
        run.font.color.rgb = RGBColor(128, 128, 128)
        
        # Save mechanism
        safe_name = document_id.replace(' ', '_').replace('/', '_')
        output_path = os.path.join(self.output_dir, f"RAG_Report_{safe_name}.docx")
        doc.save(output_path)
        
        return output_path
